--------------------------------------------------------------------------------
-- LocalizationV21 (v20.150) — переводы новых фишек: обучение, подсказки,
-- деревья прокачки (Experienced Miner, острова, престиж), окна улучшений.
-- Подмешивается в Shared.Localization (существующие переводы не трогает).
-- Ключ - английская строка как в коде/Config, {v}/{n}/... - подстановки.
--------------------------------------------------------------------------------
return {
	ru = {
		-- ОСНОВНОЕ ОБУЧЕНИЕ
		["Hi! I'm your mining buddy"] = "Привет! Я твой напарник-шахтёр",
		["Grab your pickaxe from the hotbar"] = "Возьми кирку с панели снизу",
		["Rocks block your mine. Smash them!"] = "Камни завалили шахту. Разбей их!",
		["TAKE THE PICKAXE"] = "ВОЗЬМИ КИРКУ",
		["Tap the pickaxe or press 1"] = "Нажми на кирку или клавишу 1",
		["Nice! Boulders drop ore and money"] = "Отлично! С валунов падают руда и деньги",
		-- v20.174
		["Nice! ANY ore can drop from boulders"] = "Отлично! С валунов падает ЛЮБАЯ руда",
		["Boulders can earn you MORE money than your mine right now!"] = "Сейчас валуны дают БОЛЬШЕ денег, чем шахта!",
		["Your box is in slot 1 of the hotbar"] = "Твой ящик в 1-м слоте хотбара",
		["Take it and click to open it!"] = "Возьми его и кликни, чтобы открыть!",
		["Take the box from slot 1, click to open"] = "Возьми ящик из 1-го слота и кликни",
		["Bro, {name} costs {cost}!"] = "Бро, {name} стоит {cost}!",
		["Go earn some more money and come back!"] = "Иди подзаработай денег и возвращайся!",
		["Totems"] = "Тотемы",
		["Time for TOTEMS!"] = "Пора поставить ТОТЕМ!",
		["A totem on your base gives a bonus forever"] = "Тотем на базе даёт бонус навсегда",
		["Here's money for a Luck Totem!"] = "Держи деньги на Тотем удачи!",
		["Open TOTEMS and buy it"] = "Открой ТОТЕМЫ и купи его",
		["BUY A TOTEM"] = "КУПИ ТОТЕМ",
		["TOTEMS tab, buy the Luck Totem"] = "Вкладка ТОТЕМЫ, купи Тотем удачи",
		["Go home and take the totem from the hotbar"] = "Иди домой и возьми тотем из хотбара",
		["Click your base to place it"] = "Кликни по базе, чтобы поставить",
		["PLACE THE TOTEM"] = "ПОСТАВЬ ТОТЕМ",
		["Take the totem, click your base"] = "Возьми тотем, кликни по базе",
		["The totem works while it stands on your base!"] = "Тотем работает, пока стоит на базе!",
		["More totems = more bonus"] = "Больше тотемов = больше бонус",
		["Decorations"] = "Декор",
		["You can decorate your base now!"] = "Теперь можно украшать базу!",
		["Let's get an Ore Jar and a Storage Chest"] = "Купим банку для руды и сундук",
		["Here's money for the jar!"] = "Держи деньги на банку!",
		["Open DECOR and buy the Ore Jar"] = "Открой ДЕКОР и купи банку для руды",
		["BUY THE JAR"] = "КУПИ БАНКУ",
		["DECOR tab, buy the Ore Jar"] = "Вкладка ДЕКОР, купи банку",
		["And money for the chest!"] = "И деньги на сундук!",
		["Buy the Storage Chest"] = "Купи сундук для руды",
		["BUY THE CHEST"] = "КУПИ СУНДУК",
		["DECOR tab, buy the Storage Chest"] = "Вкладка ДЕКОР, купи сундук",
		["Go home and take the jar from the hotbar"] = "Иди домой и возьми банку из хотбара",
		["PLACE THE JAR"] = "ПОСТАВЬ БАНКУ",
		["Take the jar, click your base"] = "Возьми банку, кликни по базе",
		["The jar shows off your best ore"] = "Банка показывает твою лучшую руду",
		["Hold an ore and press PUT ORE at the jar"] = "Возьми руду в руки и нажми PUT ORE у банки",
		["PUT ORE IN THE JAR"] = "ПОЛОЖИ РУДУ В БАНКУ",
		["Hold an ore, press PUT ORE at the jar"] = "Возьми руду, нажми PUT ORE у банки",
		["Press the jar again to take the ore back"] = "Нажми на банку ещё раз, чтобы забрать руду",
		["Now place the Storage Chest"] = "Теперь поставь сундук",
		["PLACE THE CHEST"] = "ПОСТАВЬ СУНДУК",
		["Take the chest, click your base"] = "Возьми сундук, кликни по базе",
		["The chest keeps 10 stacks of ore"] = "В сундуке помещается 10 стопок руды",
		["Ore in the chest is SAFE even if you get knocked out"] = "Руда в сундуке в БЕЗОПАСНОСТИ, даже если тебя вырубят",
		["Press OPEN at the chest"] = "Нажми OPEN у сундука",
		["OPEN THE CHEST"] = "ОТКРОЙ СУНДУК",
		["Tap ore to move it in or out"] = "Нажимай на руду, чтобы класть и забирать",
		["Decorate your base however you like!"] = "Укрась базу как хочешь!",
		["Click the boulders to break them"] = "Кликай по валунам, чтобы разбить их",
		["Your mine is broken. The trader fixes it for free"] = "Шахта сломана. Торговец починит её бесплатно",
		["The mine works again!"] = "Шахта снова работает!",
		["Talk to the trader, press MINE"] = "Поговори с торговцем, нажми ШАХТА",
		["Talk to me at the mine to dig"] = "Поговори со мной у шахты, чтобы копать",
		["Tap on GREEN for more and rarer ore"] = "Попадай в ЗЕЛЁНОЕ - больше и реже руда",
		["Great haul!"] = "Отличная добыча!",
		["Talk to the miner, press LET'S DIG"] = "Поговори с шахтёром, нажми КОПАЕМ",
		["Ore goes to your backpack"] = "Руда попадает в рюкзак",
		["PICK UP ORE"] = "ПОДБЕРИ РУДУ",
		["Walk over the ore"] = "Пройди по руде",
		["Sell ore at the sell zone in the middle"] = "Продай руду в зоне продажи в центре",
		["A full backpack sells for up to x3!"] = "Полный рюкзак продаётся до x3!",
		["Go to the sell zone, press SELL ALL"] = "Иди в зону продажи, нажми ПРОДАТЬ ВСЁ",
		["Here's a bonus! Get a bigger backpack"] = "Держи бонус! Купи рюкзак побольше",
		["Dig, sell, upgrade. That's the loop!"] = "Копай, продавай, улучшай. Вот и весь цикл!",
		["BIGGER BACKPACK"] = "РЮКЗАК ПОБОЛЬШЕ",
		["Talk to the trader, press BACKPACK"] = "Поговори с торговцем, нажми РЮКЗАК",
		-- ГЛАВЫ
		["Prestige Tree"] = "Дерево престижа",
		["See the case on your base? It's the Prestige Tree"] = "Видишь сундук на базе? Это дерево престижа",
		["Here's a free Prestige Point!"] = "Держи бесплатное очко престижа!",
		["PRESTIGE TREE"] = "ДЕРЕВО ПРЕСТИЖА",
		["Open the Prestige Case"] = "Открой сундук престижа",
		["Tap STARTER MINER in the middle"] = "Нажми НАЧИНАЮЩИЙ ШАХТЁР в центре",
		["Unlock it with your point"] = "Открой его за очко",
		["Prestige later for more points"] = "Делай престиж, чтобы получать ещё очки",
		["They open new branches!"] = "Они открывают новые ветки!",
		["STARTER MINER"] = "НАЧИНАЮЩИЙ ШАХТЁР",
		["Unlock Starter Miner"] = "Открой «Начинающий шахтёр»",
		["Quests give free rewards"] = "Задания дают бесплатные награды",
		["Open MENU, then QUESTS"] = "Открой МЕНЮ, затем ЗАДАНИЯ",
		["New quests come every day!"] = "Новые задания - каждый день!",
		["QUESTS"] = "ЗАДАНИЯ",
		["New Ore"] = "Новая руда",
		["New ore is sold at the Ore Merchant"] = "Новую руду продаёт торговец рудой",
		["Press TRAVEL and pick ORE MERCHANT"] = "Нажми ПУТЕШЕСТВИЕ и выбери ТОРГОВЕЦ РУДОЙ",
		["GO TO THE MERCHANT"] = "ИДИ К ТОРГОВЦУ",
		["Press TRAVEL, pick Ore Merchant"] = "Нажми ПУТЕШЕСТВИЕ, выбери торговца рудой",
		["Your mine has only Coal and Copper"] = "В твоей шахте только уголь и медь",
		["Buy a new ore box here"] = "Купи здесь коробку с новой рудой",
		["NEW ORE"] = "НОВАЯ РУДА",
		["Buy an ore box (ORE tab)"] = "Купи коробку руды (вкладка РУДА)",
		["Take the box from the hotbar"] = "Возьми коробку с панели снизу",
		["Click to open it!"] = "Кликни, чтобы открыть!",
		["OPEN THE BOX"] = "ОТКРОЙ КОРОБКУ",
		["Take the box, click to open"] = "Возьми коробку, кликни, чтобы открыть",
		["The new ore is in your mine"] = "Новая руда уже в твоей шахте",
		["Go home and dig: TRAVEL, then YOUR RAFT"] = "Иди домой копать: ПУТЕШЕСТВИЕ, затем ТВОЙ ПЛОТ",
		["Rarer ore sells for more!"] = "Редкая руда стоит дороже!",
		["DIG IT UP"] = "ВЫКОПАЙ ЕЁ",
		["Go to the miner and dig"] = "Иди к шахтёру и копай",
		["Anvil Island"] = "Остров наковальни",
		["Islands unlock new things"] = "Острова открывают новое",
		["Anvil Island opens geodes"] = "На острове наковальни открывают жеоды",
		["ANVIL ISLAND"] = "ОСТРОВ НАКОВАЛЬНИ",
		["Buy Anvil Island at the Island Keeper"] = "Купи остров наковальни у хранителя островов",
		["Your island is behind your base"] = "Твой остров - за базой",
		["VISIT THE ISLAND"] = "ЗАГЛЯНИ НА ОСТРОВ",
		["Walk to Anvil Island"] = "Дойди до острова наковальни",
		["Open a geode at the anvil"] = "Открой жеоду на наковальне",
		["It can hold a crystal!"] = "В ней может быть кристалл!",
		["Crystals earn money on Income Island"] = "Кристаллы приносят деньги на острове дохода",
		["OPEN A GEODE"] = "ОТКРОЙ ЖЕОДУ",
		["Income Island"] = "Остров дохода",
		["Income Island makes money even offline"] = "Остров дохода приносит деньги даже офлайн",
		["Buy it at the Island Keeper"] = "Купи его у хранителя островов",
		["INCOME ISLAND"] = "ОСТРОВ ДОХОДА",
		["Buy Income Island at the Island Keeper"] = "Купи остров дохода у хранителя островов",
		["Go to your new island"] = "Иди на свой новый остров",
		["Walk to Income Island"] = "Дойди до острова дохода",
		["Put a crystal on the podium"] = "Поставь кристалл на подиум",
		["It earns money every second"] = "Он приносит деньги каждую секунду",
		["Money piles up in the safe"] = "Деньги копятся в сейфе",
		["PLACE A CRYSTAL"] = "ПОСТАВЬ КРИСТАЛЛ",
		["Use the podium, pick a crystal"] = "Подойди к подиуму, выбери кристалл",
		["Smelter"] = "Плавильня",
		["The Smelter makes ingots worth x10"] = "Плавильня делает слитки дороже в 10 раз",
		["SMELTER"] = "ПЛАВИЛЬНЯ",
		["Buy Smelter Island at the Island Keeper"] = "Купи остров плавильни у хранителя островов",
		["Go to the Smelter"] = "Иди к плавильне",
		["Walk to Smelter Island"] = "Дойди до острова плавильни",
		["Hold ore and use the furnace"] = "Возьми руду и используй печь",
		["Ingots keep mutations. Sell them!"] = "Слитки сохраняют мутации. Продавай их!",
		["Hold ore, use the furnace"] = "Возьми руду, используй печь",
		["Prestige"] = "Престиж",
		["You're ready to PRESTIGE!"] = "Ты готов к ПРЕСТИЖУ!",
		["Start over and get Prestige Points"] = "Начни заново и получи очки престижа",
		["Talk to the Prestige NPC, confirm"] = "Поговори с мэром престижа, подтверди",
		["Spend points in the Prestige Case"] = "Потрать очки в сундуке престижа",
		["Perks stay forever. Have fun!"] = "Перки остаются навсегда. Удачи!",
		["BUY A PERK"] = "КУПИ ПЕРК",
		["Open the Prestige Case, buy a perk"] = "Открой сундук престижа, купи перк",
		-- ПОДСКАЗКИ МЕХАНИК И ПЛАШКА
		["Dynamite"] = "Динамит",
		["Take it from the hotbar and click a boulder"] = "Возьми его с панели и кликни по валуну",
		["Totems"] = "Тотемы",
		["Take the totem and click your base to place it"] = "Возьми тотем и кликни по базе, чтобы поставить",
		["Crystals"] = "Кристаллы",
		["Bring the crystal to the mole at the bank"] = "Отнеси кристалл кроту у банка",
		["Income Safe"] = "Сейф дохода",
		["Your crystal fills the safe with money. Collect it!"] = "Кристалл наполняет сейф деньгами. Забери их!",
		["NEW"] = "НОВОЕ",
		["SHOW ME"] = "ПОКАЖИ",
		["GUIDES"] = "ГАЙДЫ",
		["Show me"] = "Покажи",
		-- ЗВЁЗДЫ EXPERIENCED MINER И ВЕТКИ
		["Quick Feet"] = "Быстрые ноги", ["+{v}% walk speed"] = "+{v}% к скорости ходьбы",
		["Haggler"] = "Торгаш", ["+{v}% sell price"] = "+{v}% к цене продажи",
		["Lucky Eye"] = "Зоркий глаз", ["+{v}% ore luck"] = "+{v}% к удаче руды",
		["Strength"] = "Сила", ["+{v}% pickaxe damage"] = "+{v}% к урону кирки",
		["CAVE"] = "ПЕЩЕРА", ["BACKPACK"] = "РЮКЗАК", ["SUPPLIES"] = "СНАРЯЖЕНИЕ",
		-- ПЕРКИ ОСТРОВОВ
		["Hot Coals"] = "Горячие угли", ["{v}% faster smelting"] = "Плавка на {v}% быстрее",
		["Pure Metal"] = "Чистый металл", ["+{v}% ingot price"] = "+{v}% к цене слитка",
		["Star Forge"] = "Звёздная кузня", ["Ingots x12 instead of x10"] = "Слитки x12 вместо x10",
		["Polished Crystal"] = "Огранённый кристалл", ["+{v}% crystal income"] = "+{v}% к доходу кристалла",
		["Bigger Safe"] = "Большой сейф", ["+{v}% safe capacity"] = "+{v}% к вместимости сейфа",
		["Golden Podium"] = "Золотой подиум", ["+25% crystal income"] = "+25% к доходу кристалла",
		["Keen Eye"] = "Острый глаз", ["+{v}% crystal chance from geodes"] = "+{v}% к шансу кристалла из жеод",
		["Lucky Strike"] = "Удачный удар", ["{v}% chance of a bonus geode reward"] = "{v}% шанс доп. награды из жеоды",
		["Master Anvil"] = "Мастер-наковальня", ["+15% bonus geode reward chance"] = "+15% к шансу доп. награды из жеоды",
		-- ПЕРКИ ПРЕСТИЖА
		["Starter Miner"] = "Начинающий шахтёр", ["+{v}% ore price and speed"] = "+{v}% к цене руды и скорости",
		["Money"] = "Деньги", ["+{v}% ore sell price"] = "+{v}% к цене продажи руды",
		["Luck"] = "Удача", ["+{v}% rare ore luck"] = "+{v}% к удаче редкой руды",
		["Mutations"] = "Мутации", ["+{v}% mutation chance"] = "+{v}% к шансу мутаций",
		["Backpack Space"] = "Место в рюкзаке", ["+{v} backpack space"] = "+{v} места в рюкзаке",
		["Swift Feet"] = "Лёгкий шаг",
		["Safe Income"] = "Доход сейфа", ["+{v}% passive income"] = "+{v}% к пассивному доходу",
		["Geode Finder"] = "Искатель жеод", ["+{v}% geode find chance"] = "+{v}% к шансу найти жеоду",
		["Treasure Nose"] = "Нюх на сокровища", ["+{v}% chest drop chance"] = "+{v}% к шансу выпадения сундука",
		["Demolition"] = "Подрывник", ["+{v}% dynamite power"] = "+{v}% к силе динамита",
		["Head Start"] = "Фора", ["Start prestige at Cave {c}"] = "Начинай престиж с пещеры {c}",
		["Prestige Master"] = "Мастер престижа", ["+{v} prestige points per prestige"] = "+{v} очков за каждый престиж",
		["Nest Egg"] = "Заначка", ["Start each prestige with ${v}"] = "Начинай каждый престиж с ${v}",
		["Bargain Hunter"] = "Охотник за скидками", ["-{v}% ore box price"] = "-{v}% к цене коробок руды",
		["ECONOMY"] = "ЭКОНОМИКА", ["FORTUNE"] = "УДАЧА", ["UTILITY"] = "ПОЛЬЗА", ["MASTERY"] = "МАСТЕРСТВО",
		-- ОСТРОВА
		["Smelter Island"] = "Остров плавильни",
		["Smelt ore into ingots worth x10. Rarer ore takes longer - up to 10 minutes."] = "Плавь руду в слитки дороже в 10 раз. Редкая руда плавится дольше - до 10 минут.",
		["SMELT ORE INTO x10 INGOTS"] = "ПЛАВЬ РУДУ В СЛИТКИ x10",
		["Ore → ingot worth x10"] = "Руда → слиток дороже в 10 раз",
		["Keeps the ore and its mutations"] = "Сохраняет руду и её мутации",
		["Upgrade to smelt up to 5 ores at once"] = "Улучшай, чтобы плавить до 5 руд сразу",
		["Needed for Prestige"] = "Нужен для престижа",
		["Crystal podium + money safe. Your crystal earns money even while you're offline."] = "Подиум для кристалла + сейф. Кристалл приносит деньги, даже когда ты офлайн.",
		["CRYSTAL INCOME + MONEY SAFE"] = "ДОХОД С КРИСТАЛЛА + СЕЙФ",
		["It earns money - even offline"] = "Приносит деньги - даже офлайн",
		["Collect the cash from the safe"] = "Забирай деньги из сейфа",
		["Unlocks geode opening. Crack geodes to find crystals."] = "Открывает раскол жеод. Раскалывай жеоды и находи кристаллы.",
		["OPEN GEODES HERE"] = "ЗДЕСЬ ОТКРЫВАЮТ ЖЕОДЫ",
		["Open geodes from your vault"] = "Открывай жеоды из хранилища",
		["Find crystals for your Income Island"] = "Находи кристаллы для острова дохода",
		["Clay Furnace"] = "Глиняная печь", ["Brick Furnace"] = "Кирпичная печь", ["Iron Forge"] = "Железная кузня", ["Magma Foundry"] = "Магмовая плавильня",
		-- ОКНА УЛУЧШЕНИЙ И ДЕРЕВЬЯ
		["Code redeemed! Reward is active"] = "Код активирован! Награда действует",
		["Free! Holds {a} ore"] = "Бесплатно! Вмещает {a} руды",
		["Free!"] = "Бесплатно!",
		["More luck, {n} ore per dig"] = "Больше удачи, {n} руды за заход",
		["New ore: {name}"] = "Новая руда: {name}",
		["Space {a} → {b}"] = "Место {a} → {b}",
		["{name}: damage {a} → {b}"] = "{name}: урон {a} → {b}",
		["Damage {a} → {b}"] = "Урон {a} → {b}",
		["Small · Medium · Mega"] = "Малый · Средний · Мега",
		["LV {tier}/{max}"] = "УР {tier}/{max}",
		["Cave {cap} is the limit for now"] = "Пока предел - пещера {cap}",
		["GET IT FREE"] = "ПОЛУЧИ БЕСПЛАТНО",
		["Mine level"] = "Уровень шахты", ["Ore per dig"] = "Руды за заход", ["Rare ore luck"] = "Удача редкой руды",
		["Cave"] = "Пещера", ["Avg ore price"] = "Средняя цена руды", ["New ore"] = "Новая руда",
		["Backpack space"] = "Место в рюкзаке", ["Full backpack"] = "Полный рюкзак", ["Slowdown"] = "Замедление", ["None"] = "Нет",
		["Cargo space"] = "Место для груза", ["Cart health"] = "Прочность тележки", ["Full cart"] = "Полная тележка",
		["Damage"] = "Урон", ["Ore knocked per hit"] = "Руды выбивается за удар", ["Ore in hands"] = "Руда в руках",
		["Boulders up to tier"] = "Валуны до тира",
		["Breaks boulders. Knocks players down."] = "Ломает валуны. Сбивает игроков с ног.",
		["In bag: {n}/{max}"] = "В сумке: {n}/{max}", ["Radius {n}"] = "Радиус {n}", ["Knockdown {n}s"] = "Нокдаун {n}с", ["Cooldown {n}s"] = "Перезарядка {n}с",
		["CAVE {n}"] = "ПЕЩЕРА {n}", ["BAG FULL"] = "СУМКА ПОЛНА",
		["A new upgrade branch will live here."] = "Здесь появится новая ветка улучшений.",
		["NEED PRESTIGE"] = "НУЖЕН ПРЕСТИЖ", ["FREE"] = "БЕСПЛАТНО", ["GET YOUR CART"] = "ЗАБЕРИ ТЕЛЕЖКУ",
		["Tiers unlock new ore and power. Stars give small bonuses. Tap any circle."] = "Тиры открывают новую руду и силу. Звёзды дают небольшие бонусы. Нажми на любой кружок.",
		["Level"] = "Уровень", ["Next"] = "Дальше", ["Unlocks at cave"] = "Откроется в пещере", ["You have"] = "У тебя",
		["BUY 1"] = "КУПИТЬ 1", ["DETAILS"] = "ПОДРОБНЕЕ", ["TIER"] = "ТИР",
		["Already yours."] = "Уже твоё.", ["Buy tier {n} first."] = "Сначала купи тир {n}.", ["NEXT UPGRADE"] = "СЛЕДУЮЩЕЕ УЛУЧШЕНИЕ",
		["Cave limit reached - talk to the Prestige Mayor to go deeper!"] = "Предел пещеры - поговори с мэром престижа, чтобы копать глубже!",
		["The CAVE unlocks new ore. Cart and pickaxe are boosts."] = "ПЕЩЕРА открывает новую руду. Тележка и кирка - усиления.",
		["Bought!"] = "Куплено!", ["CLICK!"] = "КЛИК!",
		["Needs {name}"] = "Нужен: {name}", ["WHAT YOU GET:"] = "ЧТО ДАЁТ:",
		["FURNACE LV {level}/{max}"] = "ПЕЧЬ УР {level}/{max}",
		["Next: {name} - smelts {slots} → {next} ores at once, a bit faster. Ingot price x{mult}."] = "Дальше: {name} - плавит {slots} → {next} руды сразу, чуть быстрее. Цена слитка x{mult}.",
		["Max level! Smelts {slots} ores at once. Ingot price x{mult}."] = "Максимум! Плавит {slots} руды сразу. Цена слитка x{mult}.",
		["PRESTIGE UNLOCKED - talk to the Prestige Mayor at your base."] = "ПРЕСТИЖ ОТКРЫТ - поговори с мэром престижа на базе.",
		["PRESTIGE LOCKED - unlock every island first."] = "ПРЕСТИЖ ЗАКРЫТ - сначала открой все острова.",
		["FINAL UPGRADE"] = "ФИНАЛЬНОЕ УЛУЧШЕНИЕ", ["Max both stars"] = "Прокачай обе звезды", ["Buy the island"] = "Купи остров",
		["UPGRADES"] = "УЛУЧШЕНИЯ", ["PRESTIGE UNLOCKED"] = "ПРЕСТИЖ ОТКРЫТ",
		["Unlock islands behind your base, then upgrade each island."] = "Открывай острова за базой, затем улучшай каждый.",
		["Smelts {slots} ores at once, a bit faster. Ingot price x{mult}."] = "Плавит {slots} руды сразу, чуть быстрее. Цена слитка x{mult}.",
		["Buy the Smelter Island first"] = "Сначала купи остров плавильни",
		["FURNACE UPGRADED!"] = "ПЕЧЬ УЛУЧШЕНА!", ["ISLAND UNLOCKED!"] = "ОСТРОВ ОТКРЫТ!",
		["1 of every {n} ore: guaranteed {m}"] = "Каждая {n}-я руда: гарантированно {m}",
		["+{v}% Luck (permanent)"] = "+{v}% к удаче (навсегда)", ["+{v}% Sell Income (permanent)"] = "+{v}% к доходу с продажи (навсегда)",
		["SHRINE · never resets"] = "СВЯТИЛИЩЕ · не сбрасывается", ["Place it on your base"] = "Поставь его на базу",
		["Start"] = "Старт", ["Needs {p}"] = "Нужен: {p}", ["PTS"] = "ОЧК",
		["Progress"] = "Прогресс", ["All story quests complete!"] = "Все сюжетные задания выполнены!",
		["COMPLETED"] = "ВЫПОЛНЕНО", ["Finish the tutorial to unlock daily quests."] = "Пройди обучение, чтобы открыть ежедневные задания.",
		["WEEKLY POINTS: {p}"] = "ОЧКИ НЕДЕЛИ: {p}",
		["Complete daily quests to earn ⭐. Chests are sent to your inventory."] = "Выполняй ежедневные задания и получай ⭐. Сундуки приходят в инвентарь.",
		["RECEIVED"] = "ПОЛУЧЕНО", ["FEATURED"] = "ХИТ",
		["SELL ORE HERE"] = "ПРОДАВАЙ РУДУ ЗДЕСЬ", ["New prices in {time}"] = "Новые цены через {time}",
		["New stock in"] = "Новый товар через", ["IN STOCK!"] = "В НАЛИЧИИ!",
		["PERKS"] = "ПЕРКИ", ["🗿 SHRINES"] = "🗿 СВЯТИЛИЩА",
		["Drag to move  •  Scroll or pinch to zoom"] = "Тяни, чтобы двигать  •  Колесо или щипок - масштаб",
		["UPGRADE"] = "УЛУЧШИТЬ", ["BUY"] = "КУПИТЬ", ["MAX"] = "МАКС", ["OWNED"] = "ЕСТЬ", ["LOCKED"] = "ЗАКРЫТО",
		["PRESTIGE"] = "ПРЕСТИЖ", ["ISLANDS"] = "ОСТРОВА", ["UPGRADES "] = "УЛУЧШЕНИЯ ", ["Explosives"] = "Взрывчатка",
		["EXPERIENCED MINER"] = "ОПЫТНЫЙ ШАХТЁР", ["Everything resets on prestige"] = "При престиже всё сбрасывается",
		["Island Keeper"] = "Хранитель островов", ["START"] = "СТАРТ", ["Your journey begins here."] = "Здесь начинается твой путь.",
		["Max level"] = "Максимальный уровень", ["Not enough money"] = "Не хватает денег", ["Slow down"] = "Не так быстро",
		["Buy the island first"] = "Сначала купи остров", ["Max both stars first"] = "Сначала прокачай обе звезды",
	},
	es = {
		["Hi! I'm your mining buddy"] = "¡Hola! Soy tu compañero minero",
		["Grab your pickaxe from the hotbar"] = "Toma tu pico de la barra",
		["Rocks block your mine. Smash them!"] = "Las rocas bloquean tu mina. ¡Rómpelas!",
		["TAKE THE PICKAXE"] = "TOMA EL PICO",
		["Tap the pickaxe or press 1"] = "Toca el pico o pulsa 1",
		["Nice! Boulders drop ore and money"] = "¡Bien! Las rocas sueltan mineral y dinero",
		["Click the boulders to break them"] = "Haz clic en las rocas para romperlas",
		["Your mine is broken. The trader fixes it for free"] = "Tu mina está rota. El comerciante la arregla gratis",
		["The mine works again!"] = "¡La mina funciona otra vez!",
		["Talk to the trader, press MINE"] = "Habla con el comerciante, pulsa MINA",
		["Talk to me at the mine to dig"] = "Háblame en la mina para excavar",
		["Tap on GREEN for more and rarer ore"] = "Toca en VERDE para más mineral y más raro",
		["Great haul!"] = "¡Gran botín!",
		["Talk to the miner, press LET'S DIG"] = "Habla con el minero, pulsa ¡A EXCAVAR!",
		["Ore goes to your backpack"] = "El mineral va a tu mochila",
		["PICK UP ORE"] = "RECOGE EL MINERAL",
		["Walk over the ore"] = "Camina sobre el mineral",
		["Sell ore at the sell zone in the middle"] = "Vende el mineral en la zona de venta del centro",
		["A full backpack sells for up to x3!"] = "¡Una mochila llena se vende hasta x3!",
		["Go to the sell zone, press SELL ALL"] = "Ve a la zona de venta, pulsa VENDER TODO",
		["Here's a bonus! Get a bigger backpack"] = "¡Un regalo! Consigue una mochila más grande",
		["Dig, sell, upgrade. That's the loop!"] = "Excava, vende, mejora. ¡Ese es el ciclo!",
		["BIGGER BACKPACK"] = "MOCHILA MÁS GRANDE",
		["Talk to the trader, press BACKPACK"] = "Habla con el comerciante, pulsa MOCHILA",
		["Prestige Tree"] = "Árbol de prestigio",
		["See the case on your base? It's the Prestige Tree"] = "¿Ves el cofre en tu base? Es el árbol de prestigio",
		["Here's a free Prestige Point!"] = "¡Toma un punto de prestigio gratis!",
		["PRESTIGE TREE"] = "ÁRBOL DE PRESTIGIO",
		["Open the Prestige Case"] = "Abre el cofre de prestigio",
		["Tap STARTER MINER in the middle"] = "Toca MINERO NOVATO en el centro",
		["Unlock it with your point"] = "Desbloquéalo con tu punto",
		["Prestige later for more points"] = "Haz prestigio más tarde para más puntos",
		["They open new branches!"] = "¡Abren nuevas ramas!",
		["STARTER MINER"] = "MINERO NOVATO",
		["Unlock Starter Miner"] = "Desbloquea Minero novato",
		["Quests give free rewards"] = "Las misiones dan recompensas gratis",
		["Open MENU, then QUESTS"] = "Abre MENÚ y luego MISIONES",
		["New quests come every day!"] = "¡Hay misiones nuevas cada día!",
		["QUESTS"] = "MISIONES",
		["New Ore"] = "Mineral nuevo",
		["New ore is sold at the Ore Merchant"] = "El mineral nuevo lo vende el comerciante de mineral",
		["Press TRAVEL and pick ORE MERCHANT"] = "Pulsa VIAJAR y elige COMERCIANTE",
		["GO TO THE MERCHANT"] = "VE AL COMERCIANTE",
		["Press TRAVEL, pick Ore Merchant"] = "Pulsa VIAJAR, elige el comerciante",
		["Your mine has only Coal and Copper"] = "Tu mina solo tiene carbón y cobre",
		["Buy a new ore box here"] = "Compra aquí una caja de mineral nuevo",
		["NEW ORE"] = "MINERAL NUEVO",
		["Buy an ore box (ORE tab)"] = "Compra una caja de mineral (pestaña MINERAL)",
		["Take the box from the hotbar"] = "Toma la caja de la barra",
		["Click to open it!"] = "¡Haz clic para abrirla!",
		["OPEN THE BOX"] = "ABRE LA CAJA",
		["Take the box, click to open"] = "Toma la caja, haz clic para abrirla",
		["The new ore is in your mine"] = "El mineral nuevo ya está en tu mina",
		["Go home and dig: TRAVEL, then YOUR RAFT"] = "Vuelve a casa a excavar: VIAJAR y luego TU BALSA",
		["Rarer ore sells for more!"] = "¡El mineral raro vale más!",
		["DIG IT UP"] = "EXCÁVALO",
		["Go to the miner and dig"] = "Ve al minero y excava",
		["Anvil Island"] = "Isla del yunque",
		["Islands unlock new things"] = "Las islas desbloquean cosas nuevas",
		["Anvil Island opens geodes"] = "En la isla del yunque se abren geodas",
		["ANVIL ISLAND"] = "ISLA DEL YUNQUE",
		["Buy Anvil Island at the Island Keeper"] = "Compra la isla del yunque al guardián de islas",
		["Your island is behind your base"] = "Tu isla está detrás de tu base",
		["VISIT THE ISLAND"] = "VISITA LA ISLA",
		["Walk to Anvil Island"] = "Camina a la isla del yunque",
		["Open a geode at the anvil"] = "Abre una geoda en el yunque",
		["It can hold a crystal!"] = "¡Puede tener un cristal!",
		["Crystals earn money on Income Island"] = "Los cristales dan dinero en la isla de ingresos",
		["OPEN A GEODE"] = "ABRE UNA GEODA",
		["Income Island"] = "Isla de ingresos",
		["Income Island makes money even offline"] = "La isla de ingresos gana dinero incluso desconectado",
		["Buy it at the Island Keeper"] = "Cómprala al guardián de islas",
		["INCOME ISLAND"] = "ISLA DE INGRESOS",
		["Buy Income Island at the Island Keeper"] = "Compra la isla de ingresos al guardián de islas",
		["Go to your new island"] = "Ve a tu nueva isla",
		["Walk to Income Island"] = "Camina a la isla de ingresos",
		["Put a crystal on the podium"] = "Pon un cristal en el podio",
		["It earns money every second"] = "Gana dinero cada segundo",
		["Money piles up in the safe"] = "El dinero se acumula en la caja fuerte",
		["PLACE A CRYSTAL"] = "COLOCA UN CRISTAL",
		["Use the podium, pick a crystal"] = "Usa el podio, elige un cristal",
		["Smelter"] = "Fundición",
		["The Smelter makes ingots worth x10"] = "La fundición hace lingotes que valen x10",
		["SMELTER"] = "FUNDICIÓN",
		["Buy Smelter Island at the Island Keeper"] = "Compra la isla de fundición al guardián de islas",
		["Go to the Smelter"] = "Ve a la fundición",
		["Walk to Smelter Island"] = "Camina a la isla de fundición",
		["Hold ore and use the furnace"] = "Sostén mineral y usa el horno",
		["Ingots keep mutations. Sell them!"] = "Los lingotes conservan mutaciones. ¡Véndelos!",
		["Hold ore, use the furnace"] = "Sostén mineral, usa el horno",
		["Prestige"] = "Prestigio",
		["You're ready to PRESTIGE!"] = "¡Estás listo para el PRESTIGIO!",
		["Start over and get Prestige Points"] = "Empieza de nuevo y gana puntos de prestigio",
		["Talk to the Prestige NPC, confirm"] = "Habla con el alcalde de prestigio, confirma",
		["Spend points in the Prestige Case"] = "Gasta puntos en el cofre de prestigio",
		["Perks stay forever. Have fun!"] = "Las ventajas son para siempre. ¡Diviértete!",
		["BUY A PERK"] = "COMPRA UNA VENTAJA",
		["Open the Prestige Case, buy a perk"] = "Abre el cofre de prestigio, compra una ventaja",
		["Dynamite"] = "Dinamita",
		["Take it from the hotbar and click a boulder"] = "Tómala de la barra y haz clic en una roca",
		["Totems"] = "Tótems",
		["Take the totem and click your base to place it"] = "Toma el tótem y haz clic en tu base para colocarlo",
		["Crystals"] = "Cristales",
		["Bring the crystal to the mole at the bank"] = "Lleva el cristal al topo del banco",
		["Income Safe"] = "Caja de ingresos",
		["Your crystal fills the safe with money. Collect it!"] = "Tu cristal llena la caja fuerte de dinero. ¡Recógelo!",
		["NEW"] = "NUEVO",
		["SHOW ME"] = "MOSTRAR",
		["GUIDES"] = "GUÍAS",
		["Show me"] = "Mostrar",
		["Quick Feet"] = "Pies rápidos", ["+{v}% walk speed"] = "+{v}% velocidad al caminar",
		["Haggler"] = "Regateador", ["+{v}% sell price"] = "+{v}% precio de venta",
		["Lucky Eye"] = "Ojo afortunado", ["+{v}% ore luck"] = "+{v}% suerte de mineral",
		["Strength"] = "Fuerza", ["+{v}% pickaxe damage"] = "+{v}% daño del pico",
		["CAVE"] = "CUEVA", ["BACKPACK"] = "MOCHILA", ["SUPPLIES"] = "SUMINISTROS",
		["Hot Coals"] = "Brasas", ["{v}% faster smelting"] = "Fundición {v}% más rápida",
		["Pure Metal"] = "Metal puro", ["+{v}% ingot price"] = "+{v}% precio del lingote",
		["Star Forge"] = "Forja estelar", ["Ingots x12 instead of x10"] = "Lingotes x12 en vez de x10",
		["Polished Crystal"] = "Cristal pulido", ["+{v}% crystal income"] = "+{v}% ingresos del cristal",
		["Bigger Safe"] = "Caja más grande", ["+{v}% safe capacity"] = "+{v}% capacidad de la caja",
		["Golden Podium"] = "Podio dorado", ["+25% crystal income"] = "+25% ingresos del cristal",
		["Keen Eye"] = "Vista aguda", ["+{v}% crystal chance from geodes"] = "+{v}% probabilidad de cristal en geodas",
		["Lucky Strike"] = "Golpe de suerte", ["{v}% chance of a bonus geode reward"] = "{v}% de premio extra en geodas",
		["Master Anvil"] = "Yunque maestro", ["+15% bonus geode reward chance"] = "+15% de premio extra en geodas",
		["Starter Miner"] = "Minero novato", ["+{v}% ore price and speed"] = "+{v}% precio del mineral y velocidad",
		["Money"] = "Dinero", ["+{v}% ore sell price"] = "+{v}% precio de venta del mineral",
		["Luck"] = "Suerte", ["+{v}% rare ore luck"] = "+{v}% suerte de mineral raro",
		["Mutations"] = "Mutaciones", ["+{v}% mutation chance"] = "+{v}% probabilidad de mutación",
		["Backpack Space"] = "Espacio de mochila", ["+{v} backpack space"] = "+{v} espacio de mochila",
		["Swift Feet"] = "Paso ágil",
		["Safe Income"] = "Ingreso de la caja", ["+{v}% passive income"] = "+{v}% ingreso pasivo",
		["Geode Finder"] = "Buscageodas", ["+{v}% geode find chance"] = "+{v}% probabilidad de geoda",
		["Treasure Nose"] = "Olfato de tesoros", ["+{v}% chest drop chance"] = "+{v}% probabilidad de cofre",
		["Demolition"] = "Demolición", ["+{v}% dynamite power"] = "+{v}% poder de dinamita",
		["Head Start"] = "Ventaja inicial", ["Start prestige at Cave {c}"] = "Empieza el prestigio en la cueva {c}",
		["Prestige Master"] = "Maestro del prestigio", ["+{v} prestige points per prestige"] = "+{v} puntos por prestigio",
		["Nest Egg"] = "Ahorros", ["Start each prestige with ${v}"] = "Empieza cada prestigio con ${v}",
		["Bargain Hunter"] = "Cazaofertas", ["-{v}% ore box price"] = "-{v}% precio de cajas de mineral",
		["ECONOMY"] = "ECONOMÍA", ["FORTUNE"] = "FORTUNA", ["UTILITY"] = "UTILIDAD", ["MASTERY"] = "MAESTRÍA",
		["Smelter Island"] = "Isla de fundición",
		["Smelt ore into ingots worth x10. Rarer ore takes longer - up to 10 minutes."] = "Funde mineral en lingotes que valen x10. El mineral raro tarda más, hasta 10 minutos.",
		["SMELT ORE INTO x10 INGOTS"] = "FUNDE MINERAL EN LINGOTES x10",
		["Ore → ingot worth x10"] = "Mineral → lingote que vale x10",
		["Keeps the ore and its mutations"] = "Conserva el mineral y sus mutaciones",
		["Upgrade to smelt up to 5 ores at once"] = "Mejora para fundir hasta 5 minerales a la vez",
		["Needed for Prestige"] = "Necesario para el prestigio",
		["Crystal podium + money safe. Your crystal earns money even while you're offline."] = "Podio de cristal + caja fuerte. Tu cristal gana dinero incluso desconectado.",
		["CRYSTAL INCOME + MONEY SAFE"] = "INGRESOS DE CRISTAL + CAJA FUERTE",
		["It earns money - even offline"] = "Gana dinero, incluso desconectado",
		["Collect the cash from the safe"] = "Recoge el dinero de la caja fuerte",
		["Unlocks geode opening. Crack geodes to find crystals."] = "Desbloquea abrir geodas. Rómpelas para encontrar cristales.",
		["OPEN GEODES HERE"] = "ABRE GEODAS AQUÍ",
		["Open geodes from your vault"] = "Abre geodas de tu bóveda",
		["Find crystals for your Income Island"] = "Encuentra cristales para tu isla de ingresos",
		["Clay Furnace"] = "Horno de arcilla", ["Brick Furnace"] = "Horno de ladrillo", ["Iron Forge"] = "Forja de hierro", ["Magma Foundry"] = "Fundición de magma",
		["Code redeemed! Reward is active"] = "¡Código canjeado! La recompensa está activa",
		["Free! Holds {a} ore"] = "¡Gratis! Lleva {a} minerales",
		["Free!"] = "¡Gratis!",
		["More luck, {n} ore per dig"] = "Más suerte, {n} minerales por excavación",
		["New ore: {name}"] = "Mineral nuevo: {name}",
		["Space {a} → {b}"] = "Espacio {a} → {b}",
		["{name}: damage {a} → {b}"] = "{name}: daño {a} → {b}",
		["Damage {a} → {b}"] = "Daño {a} → {b}",
		["Small · Medium · Mega"] = "Pequeña · Mediana · Mega",
		["LV {tier}/{max}"] = "NV {tier}/{max}",
		["Cave {cap} is the limit for now"] = "Por ahora el límite es la cueva {cap}",
		["GET IT FREE"] = "CONSÍGUELO GRATIS",
		["Mine level"] = "Nivel de mina", ["Ore per dig"] = "Mineral por excavación", ["Rare ore luck"] = "Suerte de mineral raro",
		["Cave"] = "Cueva", ["Avg ore price"] = "Precio medio", ["New ore"] = "Mineral nuevo",
		["Backpack space"] = "Espacio de mochila", ["Full backpack"] = "Mochila llena", ["Slowdown"] = "Lentitud", ["None"] = "Ninguna",
		["Cargo space"] = "Espacio de carga", ["Cart health"] = "Vida del carro", ["Full cart"] = "Carro lleno",
		["Damage"] = "Daño", ["Ore knocked per hit"] = "Mineral por golpe", ["Ore in hands"] = "Mineral en las manos",
		["Boulders up to tier"] = "Rocas hasta el nivel",
		["Breaks boulders. Knocks players down."] = "Rompe rocas. Derriba jugadores.",
		["In bag: {n}/{max}"] = "En la bolsa: {n}/{max}", ["Radius {n}"] = "Radio {n}", ["Knockdown {n}s"] = "Derribo {n}s", ["Cooldown {n}s"] = "Recarga {n}s",
		["CAVE {n}"] = "CUEVA {n}", ["BAG FULL"] = "BOLSA LLENA",
		["A new upgrade branch will live here."] = "Aquí habrá una nueva rama de mejoras.",
		["NEED PRESTIGE"] = "NECESITAS PRESTIGIO", ["FREE"] = "GRATIS", ["GET YOUR CART"] = "CONSIGUE TU CARRO",
		["Tiers unlock new ore and power. Stars give small bonuses. Tap any circle."] = "Los niveles dan mineral nuevo y poder. Las estrellas dan pequeños bonus. Toca cualquier círculo.",
		["Level"] = "Nivel", ["Next"] = "Siguiente", ["Unlocks at cave"] = "Se desbloquea en la cueva", ["You have"] = "Tienes",
		["BUY 1"] = "COMPRAR 1", ["DETAILS"] = "DETALLES", ["TIER"] = "NIVEL",
		["Already yours."] = "Ya es tuyo.", ["Buy tier {n} first."] = "Compra primero el nivel {n}.", ["NEXT UPGRADE"] = "SIGUIENTE MEJORA",
		["Cave limit reached - talk to the Prestige Mayor to go deeper!"] = "Límite de cueva: ¡habla con el alcalde de prestigio para ir más hondo!",
		["The CAVE unlocks new ore. Cart and pickaxe are boosts."] = "La CUEVA da mineral nuevo. El carro y el pico son mejoras.",
		["Bought!"] = "¡Comprado!", ["CLICK!"] = "¡CLIC!",
		["Needs {name}"] = "Requiere {name}", ["WHAT YOU GET:"] = "QUÉ OBTIENES:",
		["FURNACE LV {level}/{max}"] = "HORNO NV {level}/{max}",
		["Next: {name} - smelts {slots} → {next} ores at once, a bit faster. Ingot price x{mult}."] = "Siguiente: {name} - funde {slots} → {next} minerales a la vez, algo más rápido. Precio del lingote x{mult}.",
		["Max level! Smelts {slots} ores at once. Ingot price x{mult}."] = "¡Nivel máximo! Funde {slots} minerales a la vez. Precio del lingote x{mult}.",
		["PRESTIGE UNLOCKED - talk to the Prestige Mayor at your base."] = "PRESTIGIO DESBLOQUEADO: habla con el alcalde de prestigio en tu base.",
		["PRESTIGE LOCKED - unlock every island first."] = "PRESTIGIO BLOQUEADO: primero desbloquea todas las islas.",
		["FINAL UPGRADE"] = "MEJORA FINAL", ["Max both stars"] = "Mejora ambas estrellas al máximo", ["Buy the island"] = "Compra la isla",
		["UPGRADES"] = "MEJORAS", ["PRESTIGE UNLOCKED"] = "PRESTIGIO DESBLOQUEADO",
		["Unlock islands behind your base, then upgrade each island."] = "Desbloquea islas detrás de tu base y luego mejora cada una.",
		["Smelts {slots} ores at once, a bit faster. Ingot price x{mult}."] = "Funde {slots} minerales a la vez, algo más rápido. Precio del lingote x{mult}.",
		["Buy the Smelter Island first"] = "Compra primero la isla de fundición",
		["FURNACE UPGRADED!"] = "¡HORNO MEJORADO!", ["ISLAND UNLOCKED!"] = "¡ISLA DESBLOQUEADA!",
		["1 of every {n} ore: guaranteed {m}"] = "1 de cada {n} minerales: {m} garantizado",
		["+{v}% Luck (permanent)"] = "+{v}% suerte (permanente)", ["+{v}% Sell Income (permanent)"] = "+{v}% ingresos por venta (permanente)",
		["SHRINE · never resets"] = "SANTUARIO · nunca se reinicia", ["Place it on your base"] = "Colócalo en tu base",
		["Start"] = "Inicio", ["Needs {p}"] = "Requiere {p}", ["PTS"] = "PTS",
		["Progress"] = "Progreso", ["All story quests complete!"] = "¡Todas las misiones de historia completadas!",
		["COMPLETED"] = "COMPLETADO", ["Finish the tutorial to unlock daily quests."] = "Termina el tutorial para desbloquear misiones diarias.",
		["WEEKLY POINTS: {p}"] = "PUNTOS SEMANALES: {p}",
		["Complete daily quests to earn ⭐. Chests are sent to your inventory."] = "Completa misiones diarias para ganar ⭐. Los cofres van a tu inventario.",
		["RECEIVED"] = "RECIBIDO", ["FEATURED"] = "DESTACADO",
		["SELL ORE HERE"] = "VENDE MINERAL AQUÍ", ["New prices in {time}"] = "Nuevos precios en {time}",
		["New stock in"] = "Nuevo stock en", ["IN STOCK!"] = "¡EN STOCK!",
		["PERKS"] = "VENTAJAS", ["🗿 SHRINES"] = "🗿 SANTUARIOS",
		["Drag to move  •  Scroll or pinch to zoom"] = "Arrastra para mover  •  Rueda o pellizco para zoom",
		["UPGRADE"] = "MEJORAR", ["BUY"] = "COMPRAR", ["MAX"] = "MÁX", ["OWNED"] = "TUYO", ["LOCKED"] = "BLOQUEADO",
		["PRESTIGE"] = "PRESTIGIO", ["ISLANDS"] = "ISLAS", ["Explosives"] = "Explosivos",
		["EXPERIENCED MINER"] = "MINERO EXPERTO", ["Everything resets on prestige"] = "Todo se reinicia con el prestigio",
		["Island Keeper"] = "Guardián de islas", ["START"] = "INICIO", ["Your journey begins here."] = "Tu viaje empieza aquí.",
		["Max level"] = "Nivel máximo", ["Not enough money"] = "No tienes suficiente dinero", ["Slow down"] = "Más despacio",
		["Buy the island first"] = "Compra primero la isla", ["Max both stars first"] = "Primero mejora ambas estrellas al máximo",
	},
}
